
package movie_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class admin_addmovie extends javax.swing.JFrame {
    public String hr;
    public String name;
    public String director;
    public String ST;
    public String ED;
    public String price;
    public String movie_id;




    public admin_addmovie() {
        initComponents();
         Show_data();
    }

    public void clear(){
        txt_movie.setText("");
        txt_director.setText("");
        start_date.setDate(null);
        end_date.setDate(null);
        txt_price.setText("");
        lbl_id.setText("");
        txt_hr.setText("");
  
        }

    public void Show_data() {
        DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();

            try {
            
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/movie_db","root","");
              Statement st=conn.createStatement();
              String query="SELECT * FROM `movie_table`";
              ResultSet rs=st.executeQuery(query);
     
   
                 while(rs.next()){

                     movie_id=String.valueOf(rs.getInt("movie_id"));
                     name=rs.getString("movie_title");
                     director=rs.getString("director");
                     hr=rs.getString("duration");
                     ST=String.valueOf(rs.getDate("start_date"));
                     ED=String.valueOf(rs.getDate("end_date"));
                     price=String.valueOf(rs.getInt("price"));
                     String tbData[]={movie_id,name,director,hr,ST,ED,price};
                     tblModel.addRow(tbData);
                 }

            }

            catch (Exception er) {System.err.println(er);}


 
    }
  
  
    public void add_data() {
        DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();

        try {
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/movie_db","root","");
              Statement st=conn.createStatement();
              String query="SELECT * FROM `movie_table`";
              ResultSet rs=st.executeQuery(query);

              while(rs.next()){

                 movie_id=String.valueOf(rs.getInt("movie_id"));
                 name=rs.getString("movie_title");
                 director=rs.getString("director");
                 hr=rs.getString("duration");
                 ST=String.valueOf(rs.getDate("start_date"));
                 ED=String.valueOf(rs.getDate("end_date"));
                 price=String.valueOf(rs.getInt("price"));
              }

               String tbData[]={movie_id,name,director,hr,ST,ED,price};
                   tblModel.addRow(tbData);


        }

        catch (Exception er) {System.err.println(er);}

    }

    public void fetchdata(){

        try{
    
             DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();

             movie_id=tblModel.getValueAt(jTable1.getSelectedRow(),0).toString();
             name=tblModel.getValueAt(jTable1.getSelectedRow(),1).toString();
             director=tblModel.getValueAt(jTable1.getSelectedRow(),2).toString();
             hr=tblModel.getValueAt(jTable1.getSelectedRow(),3).toString();
             ST=tblModel.getValueAt(jTable1.getSelectedRow(),4).toString();
             ED=tblModel.getValueAt(jTable1.getSelectedRow(),5).toString();
             price=tblModel.getValueAt(jTable1.getSelectedRow(),6).toString();
             lbl_id.setText(movie_id);
             txt_movie.setText(name);
             txt_director.setText(director);
             txt_hr.setText(hr);
             txt_price.setText(price);

             ((JTextField)start_date.getDateEditor().getUiComponent()).setText(ST);
             ((JTextField)end_date.getDateEditor().getUiComponent()).setText(ED);

        }

        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_movie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        start_date = new com.toedter.calendar.JDateChooser();
        txt_director = new javax.swing.JTextField();
        end_date = new com.toedter.calendar.JDateChooser();
        txt_price = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_hr = new javax.swing.JTextField();
        srch_btn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Down Town Tickets");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_movie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movie (Time) - Hall No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txt_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_movieActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Movie", "Director", "HR", "Start Date", "End Date", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(51, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTable1.setShowGrid(true);
        jTable1.setShowHorizontalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        start_date.setBackground(new java.awt.Color(255, 255, 255));
        start_date.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Start Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        start_date.setDateFormatString("y-MM-d");

        txt_director.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Director", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txt_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_directorActionPerformed(evt);
            }
        });

        end_date.setBackground(new java.awt.Color(255, 255, 255));
        end_date.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "End Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        end_date.setDateFormatString("y-MM-d");

        txt_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_price.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRICE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 204, 51))); // NOI18N
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        btn_insert.setBackground(new java.awt.Color(204, 204, 204));
        btn_insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/insert.png"))); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(204, 204, 204));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/update.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/Delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(204, 204, 204));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/clear.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_id.setText("ID.NO");

        btn_back.setBackground(new java.awt.Color(204, 204, 204));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/back.png"))); // NOI18N
        btn_back.setText("Logout");
        btn_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/film-reel.png"))); // NOI18N
        jLabel3.setText("Down Town Ticket");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("List Of Movies");

        txt_hr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hr Duration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txt_hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hrActionPerformed(evt);
            }
        });

        srch_btn.setBackground(new java.awt.Color(204, 204, 204));
        srch_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        srch_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movie_system_version5/images/search.png"))); // NOI18N
        srch_btn.setText("Search");
        srch_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        srch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(end_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_hr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(srch_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txt_director, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_movie, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt_movie, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_director, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(srch_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_id)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGap(5, 5, 5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_hr, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_movieActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void txt_directorActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {
              hr=txt_hr.getText();
              name=txt_movie.getText();
              director=txt_director.getText();
              ST  = ((JTextField)start_date.getDateEditor().getUiComponent()).getText();
              ED  = ((JTextField)end_date.getDateEditor().getUiComponent()).getText();
              price=txt_price.getText();

           if(name.equals("")|| director.equals("")|| ST.equals("")|| ED.equals("")|| hr.equals("")||
              price.equals("")) {

                 JOptionPane.showMessageDialog(null, "Fill all fields", "Warning",
                 JOptionPane.WARNING_MESSAGE);
           }

           else{

               Date fday=start_date.getDate();
               Date sday=end_date.getDate();
               Date date2 = new Date();
               int comparison = fday.compareTo(sday);

                if(comparison<=0){

                   try{
                     Class.forName("com.mysql.cj.jdbc.Driver");
                     Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/movie_db","root","");
                     Statement stmt=conn.createStatement();

                     String sql="INSERT INTO `movie_table`(`movie_title`,`director`,`duration`,`start_date`, `end_date`, `price`)"
                        + " VALUES ('"+name+"','"+director+"','"+hr+"','"+ST+"','"+ED+"','"+Double.parseDouble(price)+"')";
                     stmt.executeUpdate(sql);
                     JOptionPane.showMessageDialog(null,"Successfully");
                     add_data();
                     clear();

                      }
                   catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);}

                }

                else{
                       JOptionPane.showMessageDialog(null, "Invalid End Date ", "Warning",
                        JOptionPane.WARNING_MESSAGE);

                        }
                   }
    }

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {

           DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();

           name=txt_movie.getText();
           director=txt_director.getText();
           ST  = ((JTextField)start_date.getDateEditor().getUiComponent()).getText();
           ED  = ((JTextField)end_date.getDateEditor().getUiComponent()).getText();
           price=txt_price.getText();
           hr=txt_hr.getText();

                 if(name.equals("")|| director.equals("")|| ST.equals("")|| ED.equals("")|| hr.equals("")||
                    price.equals("")) {

                     JOptionPane.showMessageDialog(null,"Please Select Data");
                 }

                 else{
                        try{

                            int num=Integer.parseInt(lbl_id.getText());
                            Class.forName("com.mysql.cj.jdbc.Driver");
                            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/movie_db","root","");
                            Statement stmt=conn.createStatement();
                            String sql="UPDATE `movie_table` SET "
                                    + "`movie_title`='"+name+"',"
                                    + "`director`='"+director+"',"
                                      + "`duration`='"+hr+"',"
                                    + "`start_date`='"+ST+"',"
                                    + "`end_date`='"+ED+"',"
                                    + "`price`='"+price+"' "
                                    + "WHERE movie_id='"+num+"'";

                            stmt.executeUpdate(sql);
                            tblModel.setValueAt(lbl_id.getText(),jTable1.getSelectedRow(),0);
                            tblModel.setValueAt(name,jTable1.getSelectedRow(),1);
                            tblModel.setValueAt(director,jTable1.getSelectedRow(),2);
                            tblModel.setValueAt(hr,jTable1.getSelectedRow(),3);
                            tblModel.setValueAt(ST,jTable1.getSelectedRow(),4);
                            tblModel.setValueAt(ED,jTable1.getSelectedRow(),5);
                            tblModel.setValueAt(price,jTable1.getSelectedRow(),6);
                            JOptionPane.showMessageDialog(null,"Update successfully");
                            btn_delete.setEnabled(false);
                                    btn_update.setEnabled(false);
                             btn_insert.setEnabled(true);

                            clear();
                        }

                        catch(Exception ex){
                            JOptionPane.showMessageDialog(null,ex);

                        }
                }
    }

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {

        DefaultTableModel tblModel=(DefaultTableModel) jTable1.getModel();
        name=txt_movie.getText();
        director=txt_director.getText();
        ST  = ((JTextField)start_date.getDateEditor().getUiComponent()).getText();
        ED  = ((JTextField)end_date.getDateEditor().getUiComponent()).getText();
        price=txt_price.getText();

            if(name.equals("")|| director.equals("")|| ST.equals("")|| ED.equals("")|| hr.equals("")||
               price.equals("")) {
                    JOptionPane.showMessageDialog(null,"Please Select Data");
            }
            else{

                if(jTable1.getSelectedRowCount()==1){

                    if (JOptionPane.showConfirmDialog(null, "Do you want to delete these transaction?", "Confimation",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                        try{
                            int num=Integer.parseInt(lbl_id.getText());
                            Class.forName("com.mysql.cj.jdbc.Driver");
                            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost/movie_db","root","");
                            Statement stmt=conn.createStatement();

                            String sql="DELETE FROM `movie_table` WHERE movie_id='"+num+"'";
                            tblModel.removeRow(jTable1.getSelectedRow());
                            stmt.executeUpdate(sql);
                            clear();

                            JOptionPane.showMessageDialog(null,"Delete Complete");

                        }
                        catch(Exception ex){
                            JOptionPane.showMessageDialog(null,ex);
                        }
                    }
                    else{}

                }

                else if(jTable1.getSelectedRowCount()==0){
                    JOptionPane.showMessageDialog(null,"Please Select Data ");
                }
                else{
                    if(jTable1.getRowCount()==0){
                        JOptionPane.showMessageDialog(null,"The table is Empty");
                    }
                }
            }

    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        fetchdata();
        btn_insert.setEnabled(false);
        btn_delete.setEnabled(true);
        btn_update.setEnabled(true);

    }

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        Homepage hp=new Homepage();
        hp.setVisible(true);

    }

    private void txt_hrActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {
        clear();
    }

    private void srch_btnActionPerformed(java.awt.event.ActionEvent evt) {
        srch sc=new srch();
        sc.setVisible(true);
        this.setVisible(false);
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_addmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_addmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_addmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_addmovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_addmovie().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_update;
    private com.toedter.calendar.JDateChooser end_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JButton srch_btn;
    private com.toedter.calendar.JDateChooser start_date;
    public javax.swing.JTextField txt_director;
    public javax.swing.JTextField txt_hr;
    public javax.swing.JTextField txt_movie;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
